### 해당 프로젝트내에 모든 마일스톤을 가지고옴
### /projects/{project_id}/milestones
GET http://localhost:8080/projects/2/milestones


### 해당 프로젝트내에 마일스톤을 등록함
### /projects/{project_id}/milestone
POST http://localhost:8080/projects/2/milestone
Host: localhost:8080
Content-Type: application/json

{
    "mileStoneId" : null,
	"mileStoneName" : "chanyoungtest",
	"startDate" : null,
	"endDate" : null
}

### 해당 프로젝트내에 마일스톤을 수정함
### /projects/{project_id}/milestones/{milestones_id}
PUT http://localhost:8080/projects/2/milestones/8
Host: localhost:8080
Content-Type: application/json

{
  "mileStoneName" : "test-chanyoung",
  "startDate" : "2023-06-07",
  "endDate" : "2023-06-07"
}

