### 해당 프로젝트내에 모든 마일스톤을 가지고옴
### /projects/{projectId}/milestones
GET http://localhost:8080/projects/2/milestones HTTP/1.1


### 해당 프로젝트내에 마일스톤을 등록함
### /projects/{projectId}/milestone
POST http://localhost:8080/projects/2/milestone HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "mileStoneId" : null,
	"mileStoneName" : "마일스톤 테스트",
	"startDate" : null,
	"endDate" : null
}

### 해당 프로젝트내에 마일스톤을 수정함
### /projects/{projectId}/milestones/{milestonesId}
PATCH http://localhost:8080/projects/2/milestones/12 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "mileStoneName" : "마일스톤 테스트수정",
  "startDate" : "2023-06-11",
  "endDate" : "2023-06-11"
}

### 해당 프로젝트내에 있는 마일스톤을 삭제함
### /projects/{projectId}/mildstones/{milestonesId}
DELETE http://localhost:8080/projects/2/milestones/8 HTTP/1.1


